
# [ --------------------------------------------------------------------------------------- ] #
#   -= SpigotBroadcast =-                                                                     #
#   -= Author: DevSnox =-                                                                     #
#   -= Version: 3.0-DEVELOPMENT =-                                                            #
#   -= Contact: E-mail: me.devsnox@gmail.com Discord: DevSnox#2979 =-                         #
#   -= Information's:                                                                         #
#   -= Please send exceptions per PM on spigotmc.org =-                                       #
#   -= When you use this Plugin please rate it on spigotmc.org =-                             #
# [ --------------------------------------------------------------------------------------- ] #


# { Basic - Configuration }

# { HELP: The interval of displaying messages }
  interval: 2

# { HELP: The timeunit the interval use (DAYS, HOURS, MINUTES, SECONDS) }
  timeunit: MINUTES

# { --------------------- }


# { Messages }

  # { HELP: If the prefix should be enabled }
  prefix-enabled: true

  # { HELP: The prefix displayed before every message }
  # { Don't forget the space after the prefix if you want to have a space between prefix and messages}
  prefix: "&e[&cBroadcast&e] "

  # { HELP: The list of messages. You can use all colorcodes with '&' before! }
  messages:
    '1':
      lines:
      - "&aLine one"
      - "&aLine two"
      - "&cLine tree"
    '2':
      lines:
      - "I'm a one-liner known as single as well :P"

#{ --------- }