name: SpigotBroadcast
authors: [DevSnox, Lars Artmann | LartyHD]
version: "2.0-RELEASE"
main: me.devsnox.spigotbroadcast.SpigotBroadcast
commands:
  spigotbroadcast:
    description: The control command of SpigotBroadcast