name: SpigotBroadcast
author: DevSnox
authors: [DevSnox, Lars Artmann | LartyHD]
version: "3.0-SNAPSHOT"
main: me.devsnox.spigotbroadcast.SpigotBroadcast
commands:
  spigotbroadcast:
    description: The control command of SpigotBroadcast