name: SpigotBroadcast
author: DevSnox
authors: [DevSnox, Lars Artmann | LartyHD]
version: "2.0.1-SNAPSHOT"
main: me.devsnox.spigotbroadcast.SpigotBroadcast
commands:
  spigotbroadcast:
    description: The control command of SpigotBroadcast